### ISSUE TITLE
Issue with AniDB entry connections

### ISSUE THREAD

**Issue by DerRM** [japanesemediamanager/jmmserver#118]
http://www.nyaa.se/?page=view&tid=634469 Kara no Kyoukai - Extra Chorus

Listed under Specials under Mirai Fukuin but red circle says no episode. Expand button reveals a linked file, though. [Mirai Fukuin](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=9309) has no Special except the Cinema Intro, so [Extra Chorus](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10566) should be a seperate entry.

Maybe related to: [#38](https://github.com/japanesemediamanager/jmmserver/issues/38)

**Comment by jmediamanager** [comment]
Ok I have imported and it looks fine to me.

Possibly the information on AniDB, has been fixed since you first imported the file

![snap4](https://cloud.githubusercontent.com/assets/6645153/5698405/256ecd12-9a61-11e4-9f02-956364ae362f.jpg)

![snap2](https://cloud.githubusercontent.com/assets/6645153/5698407/2f44f2a8-9a61-11e4-88db-78cf02f845a5.jpg)

**Comment by jmediamanager** [comment]
Closing, as it now seems fine to me
