### ISSUE TITLE
64bit support

### ISSUE THREAD

**Issue by scj643** [japanesemediamanager/jmmserver#143]
Building the source in 64 bit has some performance increases could it be possible to make a 64 bit release.

**Comment by maxpiva** [comment]
The current .NET (C#) Target is AnyCPU. So if you run it on a x64 machine, it'll run in 64 Bit. The C++ code used (mediainfo.dll and hasher.dll) have different dll, if you run the app on a x64 machine, it'll run the x64 compiled version (x64 directory), otherwise the x86 compiled version (x86 directory). 

Admin please close this issue.

**Comment by jmediamanager** [comment]
As above
