### ISSUE TITLE
Option To Start On Windows Startup

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver#152]
I can manually make this happen but for those who don't know how or cant having the option to have JMM Server start on Windows Startup would be nice.

**Comment by Darken5** [comment]
ok, this is a good idea. I whole heartedly approve this idea. 

Since I installed Windows 10 (from Windows 7), I havn't been able to get JMMServer to start when computer starts up. Used to just put the shortcut into the Startup folder (Win 7)... That, for some wibbly wobbly, timey wimey reason no longer works in Win 10... Tried using Task Scheduler, set it to start when computer starts up... Still no dice. Just read somewhere you have to set it to "at user log on", gonna try that. But an option already built in to JMMServer would be quite epic.

**Comment by ElementalCrisis** [comment]
Nice Doctor Who reference. :)

Haven't tried yet on Windows 10, was going to later tonight but it seems there's no need.

**Comment by Darken5** [comment]
ha ha, hoped someone would catch the reference ^^. But yea, the Startup Folder is bugged in Windows 10 still... So its not just JMM i'm havin trouble with. Can't get KODI to auto start either in win 10. If Winblows would fix their end, i'd be happy too ^^

**Comment by Animeimp** [comment]
You can use the task manager, but you have to have it wait for 1-2 minutes after login, so that the SQL server has a chance to start (If you are using SQL).  I've not found a way to start it at Windows start up, without a login process running first though.  I believe that is because the main window has to load before the JMM server starts up, which it can't do without logging in to a desktop first.

**Comment by AreFinstad** [comment]
you can have another program set an delay on the startup programs you are using. great for things like JMM that needs another program to function aswell as it can give you a quicker boot (by delaying things you dont really need right away)
http://www.thewindowsclub.com/set-delay-time-startup-programs-windows

**Comment by misakitchi** [comment]
I use "Startup Delayer" on Win7, don't know if its still working on Win10.
What do you think of Win10: good? bad?

And Animeimp i love your icone/avatar :)

**Comment by AreFinstad** [comment]
so far, Win10 works great for me.
all my programs work as expected, very small and few bugs so far aswell (only small things like the Audio Button not being at the toolbar and such (easy fix by restarting the explorer)) 
im actually quite happy with Win10 ATM, tho i do hear that other people have had issues before, aswell as older Games with SecurRom does not work well with it.... that's what i have heard anyway, haven't tested such old games just yet.

well i guess there was some issues at the start of the swap, like no DirectX and no .Net Framework (both of which had to be installed again to work)
also people have alot of issues with programs working BEFORE they updated their OS in Win10. (most of which was fixed by itself by updating obv.)

**Comment by ElementalCrisis** [comment]
Here's what you can do to get JMM Server to startup with Windows 10. 

Create a text file and add the following. 

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run]
"JMMServer"="\"JMM Server Install Path Here\\JMMServer.exe""

Where it says "JMM Server Install Path Here" put the path where JMM Server is installed. Use double slashes and leave the last part alone. 

Here's an example
"JMMServer"="\"E:\\Program Files (x86)\\JMM\\JMM Server\\JMMServer.exe\""

Save the text file and rename the extension from .txt to .reg. Then double-click the file to run and follow any prompts. Now JMM Server will start when Windows does.
