### ISSUE TITLE
Utility to hash reconciliation

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#22]
**Reported by werndlymob, Aug 9, 2012**

A new utility that goes through all files in your collection, and makes sure that the hash in the database matches the physical hash.

This is to check for corruption.
Should run on low disk priority

**Comment by Animeimp** [comment]
So looking forward to this.  I had a issue with a drive in my Synology unit, and ended up corrupting 2 different anime series.  But to verify everything else I am running a batch file that calls ffmpeg to try and encode the file to NULL, to insure the video file is playable.  Since I have 7TB of files, this is taking a long time, and if the batch file gets interrupted, I will have to call it for each individual folder.

The windows batchfile that I am using:
set ffm="C:\Program Files\ffmpeg\bin\ffmpeg.exe"
set frmt=*.mkv
cd "Z:\Anime\Sorted"
for /R %%f in (%frmt%) do %ffm% -v error -i "%%f" -f null - 2>error.log
@echo **********************************
@echo **** Press any key to finish *****
@echo **********************************
pause

Also using filebot to put a crc in the extended attributes so I can check for differences in the future faster, but again, if this could be native in JMM, that would be fantastic.  I had actually come here today to add a request for custom utilities section, where I could put items like this that JMM would call against marked entries, but having a crc check native would be so much faster.

**Comment by maxpiva** [comment]
Done in 3.7
