### ISSUE TITLE
Symbolic linked files report incorrect file size

### ISSUE THREAD

**Issue by seadivenet** [japanesemediamanager/jmmserver#268]
If a file is symbolically linked from one directory to another one, and JMM Server imports the symbolic link pointing to the real file it is able to get the correct hash, but it is unable to determine the file size. Currently any file that is symbolically linked will have a file size of 0 causing JMM Server to be unable to retrieve file information from AniDB.

**Comment by hidden4003** [comment]
I've made some research, it turns out that FileInfo.Length is 0 for symlinks. The only way to get the size is to actually open the file and read it. Since hasher is reading the file anyways maybe hasher should return the size of the data it actually hashed so that can be used in case when FileInfo returns 0?
