### ISSUE TITLE
Hashing of completed files seems to be blocked as long as they're open in uTorrent

### ISSUE THREAD

**Issue by DerRM** [japanesemediamanager/jmmserver#468]
In an earlier version of the JMMServer you could hash all the files if they have finished downloading. In the current version the hashing doesn't seem to start as long as utorrent is open and the seeding files are not removed from the queue.

**Comment by ElementalCrisis** [comment]
Hmm, if the file is in use by another program we won't be able to access it. We can look into this but I'm not sure if possible, any thoughts @maxpiva?

**Comment by da3dsoul** [comment]
We should be able to read it, but we can't rename, move, or change it in any way.

**Comment by hidden4003** [comment]
If it has exclusive lock we can't read it and it is good, as reading partially written file would lead to bad hash anyway.

**Comment by DerRM** [comment]
As I said in a previous version it was at least possible to hash files which had completed downloading. It makes sense that partially finished files should not be read because the hash isn't correspondent to the completed file.

**Comment by ElementalCrisis** [comment]
@maxpiva would know more about the hasher and how it works, he wrote it. :)

**Comment by maxpiva** [comment]
If utorrent locked the file, we will unable to hash it, that is normal os behavior, utorrent locked the file, there is nothing we can do about it. We open the file with read and no sharing. We do that to not hash partial files.

**Comment by DerRM** [comment]
This makes no sense to me at all, because by your logic I couldn't even open the file for playback which isn't the case at all. I see that it is locked for writing but hashing should only be a reading operation.

**Comment by maxpiva** [comment]
Lets rephrase,
First and foremost, the file handle is locked by uTorrent, not by us, we
cannot change uTorrent behavior.

Second, we need and non locked handle (no other program using the file), to
process the file, since
  A) We need to calculate the hash (and make sure no other program is
writing the file)
  B) In case we need to move the file, we need that no other program has an
open handle to the file, otherwise the move will fail.

So at init, if the file is locked by another program, the hash process is
not triggered. Otherwise it may cause the above problems, probably you can
open with any player, because the player will open the file with share
read, but because our needs we try to open with share NONE. in short
exclusivity.

Last time i check, i think utorrent has an option to move the file, i don't
know if after that uTorrent still lock the file, but you can try.

**Comment by DerRM** [comment]
Thank you that makes more sense now. The shared lock on the file doesn't guarantee if the file is not written, but can you somehow detect if the file is completed and can not be written anymore (I think utorrent is also integrated into jmm via WebUI) and in what case do you need to move the file for hashing? Just out of curiosity. Because all my files are downloaded to the designated place and don't need moving at all (in my case obviously).

**Comment by da3dsoul** [comment]
Unless we move the JMM Desktop utorrent interface over (and force everyone to use utorrent, which is unreasonable), which we have mixed feelings about, it can't happen. We also don't know if anything else is writing to it, like say Windows during a copy. There's not any nice way to detect if something plans to write to a file that I know of, and when hashing, we need to know the file is not going to change.

**Comment by ElementalCrisis** [comment]
uTorrent integration is hardly used in Desktop.

Just stop seeding the file for the couple minutes it takes to hash the file, not the best solution for you but it will work.
