### ISSUE TITLE
XEM: Xross Entity Map for Community Recommendations

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#48]
**Reported by CatmanIX, Mar 10, 2013**

Have you considered using http://thexem.de/ to help with cross database consolidation? It's still a bit rough around the edges but its much more robust than the current method.

**Jun 2, 2013  Are.Torrentbytes**

will help out with the linking process if it gets added.
sadly my JMM server picks wrong from time to time and i end up with screenshots from a random tvseries XD

**Jun 2, 2013 werndlymob**

Hi, I had never heard of this before.

In the latest release of JMM (just today), it includes new linking for TvDB.
This includes something like XEM, where links are approved by administrators.

But I will also look at this.

**Jun 2, 2013 CatmanIX**

It was created for use with the lad1337's fork of sickbeard for anime. There's a lot of issues with the sickbeard fork but i found xem to be rather well designed.

You can find him in the #xem channel on freenode if you need to discuss how it works and how to integrate it.

**Comment by CatmanIX** [comment]
I think if you ever switch to this it might be worth looking into allowing user customization of how their collection displays series rather than rigidly defaulting to how AniDB catalogues them.

Fore example, AniDB includes some episodes that i would consider as "specials" to be part of the main series, and which other services (particularly MAL) also call specials. First of all, this is a good reason to switch to XEM, as in the current system you can't really rectify this disparity between AniDB and MAL satisfactorily, whereas a XEM based system could do so easily. Secondly, it would be nice if i could have it customized to show it the way i prefer while browsing, moving the specials from the main series to the specials section, or even seperate them into two seperate entries.

This would probably be a rather massive overhaul though, so it might not be worth it.

**Comment by ElementalCrisis** [comment]
With Cloud Support having our own Web Cache is crucial, while this is an interesting alternative our current setup has already been fined tuned and replacing it would not be worth the extra work.
