### ISSUE TITLE
Files with different Hashes/size are marked as duplicate files

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#57]
**Reported by akinci.d, May 14, 2013**

As stated above files with different Hashes/size are marked as duplicate files. Added pictures as example

*What is the expected output? What do you see instead?*
That the files are not marked as duplicates since they are not the same file. Sometime JMM even deletes the "duplicate" without any kind of warning

![1](https://cloud.githubusercontent.com/assets/6645153/3974318/f713d8da-27f2-11e4-8983-6f414a786bf6.jpg)

![2](https://cloud.githubusercontent.com/assets/6645153/3974322/fde3e5a6-27f2-11e4-9f1b-98390f07fe04.jpg)

**Comment by ElementalCrisis** [comment]
I don't think this is actually a bug but a misunderstanding in regards to what JMM considers a duplicate file. Both of those files belong to the same series on AniDB which is why JMM considers it a duplicate, at least that is my understanding having experienced the same issue with director cuts of episodes and multiple OP/ED listed as the same OP/ED. I'm going to close this but if this is incorrect @jmediamanager please let me know.
