### ISSUE TITLE
Add Support for XBMC - Simple Support

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#7]
This issue is to add first stage (simple) support to XBMC.
Which means creating NFO files and thumbnails

XBMC uses '.nfo' files for shows. such as 'tvshow.nfo' (kept in the parent folder of the show) and 'filename.nfo' (kept in the same directory and the episode). 
xbmc also uses 'filename.tbn' files for episode thumbnails (also kept in the same directory as the episode) 
If there was a way to export all of the current library to these individual files and an option so that when you get a new file then JMM server will automatically create the corresponding nfo and tbn file then the data could be read by xbmc.

xbmc also has http access which allows for notifications to be sent to it for example if an episode is downloaded and ready to watch it can get a notification and add it to the library.

**Comment by anzerman** [comment]
Just want to throw my support behind this. 

I think an option to quickly support kodi it to add a TVDB renaming option to the JMM Server. I say quickly because I do not understand the complexities behind it and have made the naive assumption that it will be... I apologise :P

Kodi prefers and works best when using the season order as per The TVDB. Therefore if there was a way to get JMM to rename the collection to that format (Showname - SXXEXX - Episodename - etc), perhaps by adding The TVDB as a renaming source option, then Kodi would be able to scrape the files. 

Anyway keep up the good work.

**Comment by AreFinstad** [comment]
that already has its own issues here: 
https://github.com/japanesemediamanager/jmmclient/issues/85
https://github.com/japanesemediamanager/jmmclient/issues/86

**Comment by anzerman** [comment]
Ah, sorry about that. They are all closely linked it seems

**Comment by bigretromike** [comment]
There is change to this. Kodi/xbmc also support database in MySQL! Which is ideal here.
Im was trying to make plugin similar to Plex one that use REST interface but currently there is no documentation about API, and reverse engineering ain't my thing

**Comment by ElementalCrisis** [comment]
Already done, https://github.com/bigretromike/nakamoriplugin

Issue will remain open until JMM update with Nakamori support is official.

**Comment by AreFinstad** [comment]
related to metadata writeout: https://github.com/japanesemediamanager/jmmclient/issues/84
