### ISSUE TITLE
Firebird DB support

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#73]
**Reported by andyieg.andreas, Feb 13, 2014**

I would like to be able to use FirebirdDB as backend, since it has a embedded and server version, that need no code changes and a ADO/.net binding.

Its also easier to transport the database since its a single file, while the server version is easier and often faster then MySQL/SQLlite.

**Comment by maxpiva** [comment]
Okey, after exploring the options, the most suitable candidate for embedded database and free for this kind of project is RavenDB, i'm used to MongoDB, but its very difficult to get it embedded, on the other hand, RavenDB is as simple of adding a nuget. I'll start some db porting program, and create new poco classes as repository. Anyway i'm open to suggestions, NOSQL for the kind of data JMM manage is a WIN, but since the quantity of data is small for a db, we can actually use a Memory Database which could be better more better suited, but i'm not versed on possible candidates. So shoot some opinions. 

This will be of course a major refactor of the JMM Server, and refactor of the public api into REST/JSON, which mean all clients will need refactor too.

**Comment by ElementalCrisis** [comment]
From my understanding of NoSQL is that it's a lot more hands on then MySQL. You mentioned this would be much better for JMM, what would be some of the benefits to end users?

**Comment by maxpiva** [comment]
1) Speed,since there is a lot less joining and queries than normal structured database.
2) Data is stored as documents and can have any structure and subsctructures (subcollections) per example, one anime document could store everthing from the anime, take note, that nosql database can query on any subcollection. Which means you could query for the episode date inside the collections of episodes of the anime, etc.
3) Schema is dinamic, adding a property, collection, etc, to a class is dinamic, you don't have to alter the table (There is no tables :p).
4) More suitable to be consulted via services since there is less deserialization and queries involved, since data is not flat, since the structure in the database is the consumable form.
5) Since i'm looking for embedded, there is no more installing of addtional database servers, are spooky configuration issues.
6) More Maintable, since db structure is already in Cosumable form, there is no need for extra contracts or models, from serialization/deserialization.

**Comment by ElementalCrisis** [comment]
Oh wow, seems like JMM would benefit greatly from moving to RavenDB. I'm all for making JMM easier for the end user and this seems like the way to do it.

**Comment by bigretromike** [comment]
but what about data corruption. Im new to noSQL - but I had to recover some corrupted mysql tables which was succesfull.
Does it look also bright in noSQL?

**Comment by maxpiva** [comment]
It has some tools for corruption and also embedded backup system.

http://ravendb.net/docs/article-page/3.0/csharp/server/administration/backup-and-restore

**Comment by jmediamanager** [comment]
Moving to RavenDB, so closing
