### ISSUE TITLE
JMM Server 100% CPU

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#74]
**Reported by jeremie.berlioz, Apr 19, 2014**

*What steps will reproduce the problem?*

1. I launch JMM server: all is good
2. After 5-6 minutes JMM Server will suddenly use almost 100% CPU!!

*What version of the product are you using? On what operating system?*
JMM Server 3.1.32 + SQL2008
Windows 7 64bits (French)

*Please provide any additional information below.*
If i go back to JMM Server 3.1.17, i have not this problem
JMM Desktop is not launched
i try with MySQL and SQLite and same issue...

**Comment by misakitchi** [comment]
I reinstall JMM Server v3.4.2.19 with SQLite
I have no 100% CPU bug
But its so SLOW and it use now more the CPU than with MSSQL...

Perhaps there is a bug with NLog, i find this page:
https://github.com/NLog/NLog/issues/162
It seems there is a bug with Nlog v2.0
So can you update nlog to v3.0?

Thanks :)

**Comment by jmediamanager** [comment]
I can try that, for now can you try setting your logging to async?

<targets async="true">

**Comment by misakitchi** [comment]
In JMMServer.exe.Config I change

<targets>
	  <target name="file" xsi:type="File" fileName="${basedir}/logs/${shortdate}.txt" layout="[${shortdate} ${date:format=HH\:mm\:ss\:fff}] ${level}|${stacktrace} ${message}" />
	  <target name="console" xsi:type="ColoredConsole" layout="${date:format=HH\:mm\:ss}| --- ${message}" />
	</targets>

to 

<targets async="true">
	  <target name="file" xsi:type="File" fileName="${basedir}/logs/${shortdate}.txt" layout="[${shortdate} ${date:format=HH\:mm\:ss\:fff}] ${level}|${stacktrace} ${message}" />
	  <target name="console" xsi:type="ColoredConsole" layout="${date:format=HH\:mm\:ss}| --- ${message}" />
	</targets>

But no change... always CPU bug...

I m trying JMM server with MySQL and no bug so perhaps its good, but i must wait one month to see if the bug come or not

With MSSQL the bug appear after one month exactly!? If i change the computer date to one day before, no bug... so i think this bug have to do something with the date...

**Comment by misakitchi** [comment]
Part 1:
Ok so one month later...
I have the same bug with MySQL: JMM is in idle state (no queue) and use lots of CPU (50%average)
And i have same bug with SQLite but less CPU

So to recap: (in idle)
MSSQL 50% CPU
MySQL 50% CPU
SQLite 25% CPU
So its not the Database software who is bugging but its JMM Server...
I have no problem the first 31 days and the day after CPU Bug...

Part 2:
I see that with SQLite, in database folder, each seconds there is a file who appear and disappear right after! (JMMServer.db3-journal)

I make a copy, i put link th this file
https://mega.co.nz/#!mMkUgaJa!6N1kN3zRmbS8SRhOfnU27o9bTgyoHpagrppqpp7AEhw

If we open it we can see:
A n i D B   U D P U D P _ R E S P O N S E _ T R U N C   i n   1 0 9 1 , 0 6 2 4 m s   -   2 2 0    ¯þ‚ƒŽ: 1ƒEYA n i D B   U D P U D P _ C O M M A N D :   F I L E   s i z e = 5 0 0 7 9 9 8 0 8 & e d 2 k = 3 7ˆƒŽ= 1YA n i D B   U D P U D P _ R E S P O N S E _ T R U N C   i n   4 3 2 , 0 2 4 7 m s   -   2 2 0   F û.…í2 1mYA n i D B   U D P U D P _ R E S P O N S E   i n   2 4 4 , 0 1 3 9   m s   -   2 0 0   h n v C i   L O G I N   A C C E P T E D 
   2 0 1 5 - 0 4 - 0 2   2 0 : 1 9 : 2 8 ‚…í3 1ƒEYA n i D B   U D P U D P _ C O M M A N D :   F I L E   s i z e = 1 6 1 7 1 6 1 3 9 & e d 2 k = 1 3 0 E 8 2 7 9 6 D D 9 2 7 7 3 3 B C 9 2 6 7 5 7 C F 0 4 E 2 8 & f m a s k = 7 F F 8 F F F 9 F E & a m a s k = 0 0 0 0 F C C 0 & s = h n v C i 2 0 1 5 - 0 4 - 0 2   2 0 : 1 9 : 3 0 ¶ÞbS   SQLite format 3

Its an API request to AniBD i think, i m not specialist...

Part 3:
To remember this bug appear when i go from v3.1.25 to v3.1.26
So i look at the full changelog of JMM Server:
https://code.google.com/p/jmm/wiki/JMM_Alpha_Test#Version_3.1.26_%28December_21_2012%29

Version 3.1.26 (December 21 2012)
    Make sure that the 'Remove Missing Files' utility also updates the user's AniDB MyList
     Issue #138 : Option for JMM Server to change state to deleted rather than removing files from MyList when deleted from HDD
    Cache some AniDB info for use during file imports to prevent chances of a ban
    Log all API calls to AniDB into a new database table for debugging when a ban occurs
     Issue #352 : Slightly off-resolution files will now be grouped together, e.g. 1272x720 will be shown in same group as 1280x720
     Issue #176 : Empty folders are deleted from the drop folder automatically
     Issue #359 : Subtitle files are now moved from drop folder along with video file
    File Renamer - test that Video Resolution info exists now works - I(res)
    Fix to make sure duplicate files entries where the file name is actually the same are removed 

I think a little about it and i had few ideas, I think its:
- Cache some AniDB info for use during file imports to prevent chances of a ban
- Log all API calls to AniDB into a new database table for debugging when a ban occurs
Who cause this bug, because JMM is always trying to write something in database even its in idle state...

OK it was a little long... but right now i can't use JMM anymore because of this bug... :(
Since 2 months ago i can still use v3.1.25 but since the change in AniDB API i can't use it... and version > to v3.1.26 is bugging... :(
So i don't know what to do, JMM is really good but if i can't use it...

Please HELP!!! :)

**Comment by misakitchi** [comment]
Hello!
I don't know how and why but now, must of the time i don't have this CPU bug anymore! :)
Last week-end i go out on holidays and forgot to close JMMserver and my computer...
so for 2-3 days JMM was running, and when i come back JMM was not bugging (100% CPU bug)!!
And now its OK!
Sometimes i have the bug, don't know why, but on 10 launch of JMM i have about 8 OK and 2 CPU bug.
(Sorry i don't know how to explain it in english, my english is very poor...)
So i m very happy :)

**Comment by Andy2244** [comment]
I just moved my old Media PC from a Win7 to a Win10 RTM machine and now for the first time i have this bug too.

JMMServer starts and does its import job, than it idles a few minutes at 0% with no MySQL usage and suddenly JMMServer.exe is using one core at 100% until i stop it, while doing nothing in the queue or log?

![jmmserver bug](https://cloud.githubusercontent.com/assets/5340247/8756776/f15649c2-2cd4-11e5-8e48-2f38a92f29c8.jpg)


PS: I'm on Win10 RTM x64, with JMM 3.4.3.2 and MySql 5.6

**Comment by AreFinstad** [comment]
i also failed to inform about usage aswell over the months.
my JMM server is constantly using 10-15% of my CPU (a 3960-X@4.2Ghz) (alot for that CPU really when you think about the power it has)

this isnt an issue on server start, but quickly starting using load for no reason at all it seems within an hour. the server can be idle with no jobs on queue at all, heck even without a client running (except the Plex Plugin).

if this is even an larger problem in Win10 then it needs to be fixed.
they are giving us Win10 for free for almost anyone so ALOT of users will update, me included. 
(atleast when you get Win10 support it will support the phones and tablets smoother aswell at the same time)

**Comment by Andy2244** [comment]
Here is the log that might help:

https://drive.google.com/file/d/0B-4v-tWdPLgCOEZQa2lQZjA4TVE/view?usp=sharing

Between 22:47 and 22:52 all is nice and nothing to-do and 0% CPU, than the last entry will use 100% CPU time.

PS: I just noticed that after my last run it now is back at 0% CPU, so maybe "CommandRequest_SyncMyList.ProcessCommand Processing CommandRequest_SyncMyList" just takes a very long time and i always aborted it? How long should this command take for a fairly large AniDB collection?

**Comment by misakitchi** [comment]
So it seems that lots of people have this CPU Bug (lots of CPU used for nothing)!!!

For people with new CPU like 3960-X @ 4.2Ghz its only 10-15% CPU, but for me with old CPU E5300@2.6GHz its 100% CPU!!! :(

Like it said previously, did this bug appear at JMMServer v3.1.26 for you too?!!

And i was thinking to upgrade from Windows 7 to Windows 8.1 or 10 only to remove this bug lol!
But if the bug is here too... :(

I found lots of .NET and CPU Bug, but here some pages:
http://stackoverflow.com/questions/14954387/net-4-constantly-wasting-one-cpu-core-on-strongnamesignatureverification
http://stackoverflow.com/questions/13378213/visual-studio-profiler-clr-dll
Don't know if thoses pages can help because i have no skills in development... :(

Please Help! Its not me who have this bug anymore!!!

**Comment by misakitchi** [comment]
I find a way to MANUALLY remove this CPU bug, but its a pain in the ass... (don't know if the right english expression lol)

I use Process Explorer and do a suspend(/resume) on threads who are bugging of JMMServer...

Here i explain more in detail:
1) Open Process Explorer and go in threads tab of JMMServer
2) Thread are sorted by CPU by default, good, so select the first thread (it must be the thread who use the most CPU...)
3) Clic on "Suspend" button and watch your JMMServer window/process: If it is freezing, its not good => clic on "Resume" (its the same button, it just change the name...)
4) Wait suspend button appear and repeat 3) until JMMServer is not freezing
5) Repeat 3) and 4) for the next threads who have CPU bug (use lots of cpu)!!

So you can see that this method is really manual and not good...
And I don't really know why its working lol! :dancer: 

We really need i clean solution/patch

Thanks!

**Comment by misakitchi** [comment]
Here some pictures:
![jmmserver cpu bug - perf graph](https://cloud.githubusercontent.com/assets/9465756/8761086/4e1e86c4-2d3e-11e5-96d8-213dcda38277.jpg)
First peak is at 10:42, then 10:47, 10:52, 10:57, 11:02, 11:07... every 5 min
It use lots of Memory too: 1.8GB!!!

**Comment by misakitchi** [comment]
I create a Straw Poll to know how many people have this bug too:
http://strawpoll.me/4955543/

JMMServer must be in Idle: no queue (Hasher=0 General=0 Images=0) and JMMDesktop closed

You can use "Process Explorer" and watch in tab "Performance Graph"

Thx for help!

**Comment by misakitchi** [comment]
In my research on the net i find a way to force JMMServer to be in 32bit using CorFlags.exe
I m not sure but it seems to use less memory...

Sources:
https://lostechies.com/gabrielschenker/2009/10/21/force-net-application-to-run-in-32bit-process-on-64bit-os/
https://msdn.microsoft.com/fr-fr/library/ms164699(v=vs.110).aspx

You can find CorFlags.exe here:
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Bin\x64
Put CorFlags.exe in same folder that JMMServer.exe

Open cmd window (command line)
Go in JMMServer folder and put this command line:
CorFlags jmmserver.exe /32BIT+

Et Voila!

**Comment by Andy2244** [comment]
Oki i can not reproduce this bug anymore, either it was a one time occurrence of a operation that simply took very long on my old machine or it has to-do with a routing problem on my side, since i cant reach aniDB.net atm without using a VPN.

**Comment by AreFinstad** [comment]
i for one would not say that 1.6GB of RAM usage is alot at all really, but the server should lower its usage over time. it doesnt need to have everything in the ram at all time TBH.

also, quick question, i see there is alot of detail in that property picture.... what application is that anyway? can really come in handy for me i think.

**Comment by misakitchi** [comment]
Which application? "JMMServer.exe:4956 Properties"?
Its "Process Explorer":
https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx

You can take the whole pack tools: "Sysinternals Tools"
https://technet.microsoft.com/en-us/sysinternals/bb842062

Very usefull tools! :)

**Comment by AreFinstad** [comment]
thanks, didnt know about these at all TBH...... always used what windows gave me XD

**Comment by misakitchi** [comment]
AFTER MORE THAN ONE YEAR (16 MONTHS!) I FIND HOW TO REMOVE THE CPU BUG!!!!!

I m so Happy! :)
Thoses days i see that a request in SQL was causing the CPU BUG
When i remove it from SQL, the CPU bug was gone, but 5 min after that, the same request appear...
So i try lots of options in SQL Server and find one who remove bug! :)

Go in SQL Server Management Studio
Then Properties of Server, Connexions, and tick "Use query governor to prevent long-running queries" (I put 120s)

![jmmserver - cpu bug - sql](https://cloud.githubusercontent.com/assets/9465756/9027143/add1698a-3949-11e5-8687-378b829ae93e.jpg)

Et Voila! ^_^

**Comment by misakitchi** [comment]
For jmediamanager, the detail of the SQL request who is doing the bug:

In SQL Activity Monitor:
 "Process" Tab: the query detail who is bugging:
(@p0 int)DELETE FROM [LogMessage] WHERE LogMessageID = @p0

"Long queries" Tab:
SELECT this_.LogMessageID as LogMessa1_193_0_, this_.LogType as LogType193_0_, this_.LogContent as LogContent193_0_, this_.LogDate as LogDate193_0_ FROM [LogMessage] this_ ORDER BY this_.LogDate desc
=> Average Time was very high!

Sorry i don't have screens... but if you want i can do it

**Comment by jmediamanager** [comment]
Hi @misakitchi, I don't recommend changing that SQL setting.
Probably the best thing to do is delete all the rows from the log message table, which should speed up any queries.

`delete from LogMessage`

Before you do that, can you run a query to see how many rows you current have

`select count(*) from LogMessage`

I noticed a bug a few days ago around log messages, so once I fix this it should resolve your issue in the futire

**Comment by misakitchi** [comment]
I run the query in my JMM database:
select count(*) from LogMessage

Result: 561573
Yes i think the bug is here, too much logmessage...

**Comment by jmediamanager** [comment]
Yup that is too many
There is an automated process which deletes old records from that table every day (which is failing)

If you run the command to delete those messages it should fix your issue

**Comment by misakitchi** [comment]
Command is : "delete from LogMessage"?

And when i active option "Use query governor to prevent long-running queries" i don't have "last episodes" files in dashbord

**Comment by misakitchi** [comment]
Also, if anyone is seeing JMM Server using more than 0% CPU, I would recommend changing the following in the config file.

logger name="*" minlevel="Info" writeTo="file,console"/
to
<logger name="*" minlevel="Trace" writeTo="file,console"/>

Then check to logs to see if JMM Server is actually logging anything, when you think it should be doing nothing

=> its the same issue?

**Comment by jmediamanager** [comment]
yes run that delete statement
and also turn off that option

**Comment by misakitchi** [comment]
OK its working!!! :)
But for how long?!!

**Comment by Animeimp** [comment]
Check services and make sure that that the SQL agent manager is set to auto start, and is running. Then you should have to do it ever again. 

Also make sure the SQL agent service is running under your username and password rather than the default account.

**Comment by misakitchi** [comment]
SQL Agent Manager is disable in my version of SQL... :(
How can i automatise the command "delete from LogMessage" in SQL?!
Thx

**Comment by misakitchi** [comment]
I still need to do a manual cleaning of my Database, because SQL Agent Manager is disable in my version of SQL...
Any news for this bug?

Here the request i use:
USE JMMServer
--SELECT count(*) FROM LogMessage
DELETE FROM LogMessage

Help!!
